### ISSUE TITLE
Could not install package 'HDF.PInvoke 1.8.17.8'- Visual Studio 2010 Professional, Platform = Windows 7 Ultimate 32-Bit

### ISSUE THREAD

**Issue by kunalpurimkbk** [HDFGroup/HDF.PInvoke#100]
Recently, I have installed **Visual Studio 2010 Professional** on my PC. I am trying to install HDF-PInvoke Version 1.8.17.8 to my C# project using NuGet Package Manager, but it is constantly showing me the message:

**Command Used:**
Install-Package HDF.PInvoke -Version 1.8.17.8

**Message:**
Install-Package : Could not install package 'HDF.PInvoke 1.8.17.8'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0,Profile=Client', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:16
- Install-Package <<<<  HDF.PInvoke -Version 1.8.17.8
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**The platform that I am currently using is Windows 7 Ultimate 32-Bit and during installation of Visual Studio, I preferred Custom Installation and installed only Visual C#**

**Comment by JanWosnitza** [comment]
@kunalpurimkbk Do you need .Net 4.0 Client? If you switch to .Net 4.5, the package should work.

@hokb I could reproduce this error on Win10, VS 2015 Community, .Net 4.0 and .Net 4.0 Client.
Is there any reason for force .Net 4.5? I think the library could also be .Net 2.0 compatible. Wouldn't require a lot of changes.

**Comment by hokb** [comment]
Wasn't me deciding this. Don't know if there was a decision at all :) I suggest to open a new issue on it.

**Comment by JanWosnitza** [comment]
Done and branched ;)

**Comment by JanWosnitza** [comment]
@kunalpurimkbk The next (or current) release relies on .Net 2.0. So I guess your issue is solved then? If not, feel free to re-open this ticket or create a new one.
