### ISSUE TITLE
Consider automatic package generation

### ISSUE THREAD

**Issue by JanWosnitza** [HDFGroup/HDF.PInvoke#105]
Would be awesome, if all required resources to generate the NuGet package were contained in the repository and also the build process automatized.
#### Advantages
- One Click to build the project, run all unit-tests and build the package for all versions
- Documented packaging process
- All information to build the package in one place (the repo)
- Less prone to errors when building package
- Could be done on a build server
#### Disadvantages
- Requires some work to implement
- Future changes need to be automated too
#### Suggestion

I have some (good) experience with [FAKE](http://fsharp.github.io/FAKE/) and [Paket](https://fsprojects.github.io/Paket/). Would require adding some files only.

Most F# projects use the FAKE and Paket configuration and e.g. [OpenTK](https://github.com/opentk/opentk) moved to it recently.

Let me know, what you think about this :)

**Comment by JanWosnitza** [comment]
Branch https://github.com/JanWosnitza/HDF.PInvoke/tree/automate-nuget%23105 (there must be a better way to reference it!)

**Comment by gheber** [comment]
Thanks, I'll check it out!
