### ISSUE TITLE
NullReferenceException when dependencies path not set in app.config

### ISSUE THREAD

**Issue by gtaylor1981** [HDFGroup/HDF.PInvoke#112]
Resolving the native dependencies path causes a `NullReferenceException` if `AppSettings` does not contain a setting called `NativeDependenciesAbsolutePath` but does contain other settings.

The code (in 1.10.0.0) is:

```
if (ConfigurationManager.AppSettings.Count <= 0) return false; 
string pathFromAppSettings = ConfigurationManager.AppSettings[NativePathSetting].ToString(); 
```

The first line succeeds, as I have other application settings present. The second line returns null from `AppSettings[NativePathSetting]` which causes the exception when `.ToString()` is called on it.

(The workaround for now is to include an empty setting in the app.config file)

Additionally, it would be nice to be able to specify a path in the config not to the DLL itself, but to the bin32/bin64 folders. The library would then find the correct DLL to use in the same way as in the `GetDllPathFromAssembly()` method.

**Comment by JanWosnitza** [comment]
Hi @gtaylor1981 thanks for reporting.
The `NullReferenceException` should be fixed in the next version 👍 and the platform independent native path sounds good to me, too.
