### ISSUE TITLE
H5DO.append is failing

### ISSUE THREAD

**Issue by gtaylor1981** [HDFGroup/HDF.PInvoke#125]
Assert.IsTrue(H5DO.append(dataSetId, H5P.DEFAULT, 0, new IntPtr(count), typeId, ptr) >= 0); always fails. Why?

**Comment by gheber** [comment]
Can you give us an example?

**Comment by JanWosnitza** [comment]
Have you created the dataset with the chuncked storage layout?
https://support.hdfgroup.org/HDF5/Tutor/layout.html#lo-define

**Comment by gtaylor1981** [comment]
Apologies for the delay in replying.

See attached for a very simple C# example that demonstrates that `H5DO.append(...)` returns -1, despite the file being correctly appended to.

[AppendDemo.zip](https://github.com/HDFGroup/HDF.PInvoke/files/1571648/AppendDemo.zip)

**Comment by gheber** [comment]
@gtaylor1981 have you tried this with the HDF5 1.10.2 binaries? I have a similar test f711e55 , which works fine with 1.10.2. There were a few fixes for `H5DO[read,write]_chunk` in 1.10.2 that might have helped this.
