### ISSUE TITLE
Iterating through a list of groups in a HDF5 file.

### ISSUE THREAD

**Issue by ShikharMittal** [HDFGroup/HDF.PInvoke#126]
Hi,

My requirement is to parse an HDF5 file using c# application. The file is structured such that there are multiple groups in the file with random names. Each group has 2 datasets which contain data.

Could you please help me figure out how to iterate through the groups and read the data. 

As an input all I have is the HDF5 file.

Please advise. Help needed urgently.

**Comment by gheber** [comment]
What's the issue?

**Comment by ShikharMittal** [comment]
I do not have the groups information within the file. I need to loop through all the groups that exist in the file and read the data within those groups?
I am not able to figure out how to iterate through the groups in a file.

**Comment by gheber** [comment]
This is not a help forum for the use of HDF.PInvoke. Why don't you post a question to the HDF forum?

https://lists.hdfgroup.org/mailman/listinfo/hdf-forum_lists.hdfgroup.org
