### ISSUE TITLE
NuGet won't add import hdf5.targets in csproject and native components won't copy in output directory

### ISSUE THREAD

**Issue by olejniczak** [HDFGroup/HDF.PInvoke#143]
The MsBuild targets file in NuGet build directory should have a name of the package - HDF.PInvoke.targets not hdf5.targets.
After install of the HDF.PInvoke in .NET Console application project it does not add import statement in csproj file. I have created new NuGet Package and rename targets file into HDF.PInvoke.targets.
After installation csproj file have new content
`<Import Project="..\packages\HDF.PInvoke.1.10.2.1\build\HDF.PInvoke.targets" Condition="Exists('..\packages\HDF.PInvoke.1.10.2.1\build\HDF.PInvoke.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\HDF.PInvoke.1.10.2.1\build\HDF.PInvoke.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\HDF.PInvoke.1.10.2.1\build\HDF.PInvoke.targets'))" />
  </Target>`
and during build native components are copied into output directory.

**Comment by gheber** [comment]
Is this related to #142 ?

**Comment by olejniczak** [comment]
Yes. Sorry I haven't noticed that. Fix is easy: you have to rename the targets file and then it works fine.

**Comment by gheber** [comment]
👍
