### ISSUE TITLE
H5E.walk_t should have err_desc marked with [In] attribute?

### ISSUE THREAD

**Issue by marklam** [HDFGroup/HDF.PInvoke#154]
When using a [stack walking function](https://github.com/DeepMLNet/DeepNet/blob/6b91e28ab3e30de89fe76f63e2f97544a6bbd478/Tensor/Tensor/HDF5.fs#L15) in a debug build, the CLR terminates the app due to heap corruption.

I think it's a side-effect of marshalling the `error_t` structure. If the definition of [`walk_t`](https://github.com/HDFGroup/HDF.PInvoke/blob/1369c15875d5662320f565e475a125c39944c1bd/HDF5/H5Epublic.cs#L130) is changed to add the [In] attribute to err_desc:
```C#
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate herr_t walk_t
             (
             uint n,
             [In]ref H5E.error_t err_desc,
             IntPtr client_data
             );
```
then the stack-walking completes successfully.

**Comment by gheber** [comment]
Good catch. It appears that C# gets the "special" treatment and the error doesn't show in the (admittedly, dumb) unit test. I'll push out new Nu(g)Gets in a few. Let me know if that fixes the issue.

**Comment by marklam** [comment]
I couldn't create a C# unit test that showed it either :-)
I've checked the 1.10.5.1 packages, and can confirm that they do fix the problem - thanks!
