### ISSUE TITLE
Reading in Unity

### ISSUE THREAD

**Issue by mercem** [HDFGroup/HDF.PInvoke#157]
hi,

Has anyone tried to read .h5 in unity or is that even possible?

Thank you

**Comment by JanWosnitza** [comment]
Hi @mercem ,
I havn't, but it shouldn't make any issues. Unity uses Mono as runtime-environment which also allows loading native DLLs. It's possible you that need the Pro version of Unity.

**Comment by mercem** [comment]
hi @JanWosnitza 

Thank you for quick response I will inform here if I get any issues in Unity.
