### ISSUE TITLE
Question: Iterate of each attribute of object and print its information #17

### ISSUE THREAD

**Issue by LiorBanai** [HDFGroup/HDF.PInvoke#168]
HI,
I'm able to iterate over the structure of h5 file but it does not iterate over each object attributes if there any.
Is it possible to do so (and print the attributes values, types, etc)?

**Comment by JanWosnitza** [comment]
Hello @LiorBanai,
if it's only about closing all objects, you could create a Property, set it to close-strong and give it to H5Fopen.

Something along these lines (untested):
```csharp
var property = H5P.create(H5P.FILE_ACCESS);
H5P.set_fclose_degree(property, H5F.close_degree_t.STRONG);
var file = H5F.open("FILE_NAME", H5F.ACC_RDWR, property);
H5P.close(property);

// access file

H5F.close(file); // all objects opened are closed implicitly here
```
also have a look at the c documentation: [H5Pset_fclose_degree](https://support.hdfgroup.org/HDF5/doc/RM/RM_H5P.html#Property-SetFcloseDegree)
