### ISSUE TITLE
Question: Call to list all open objects and how to close all of them? #18

### ISSUE THREAD

**Issue by LiorBanai** [HDFGroup/HDF.PInvoke#169]
Hi,

is there are method that list all opens objects with its information?
can those be close in other call or they need to be closed individually?

**Comment by JanWosnitza** [comment]
Hello @LiorBanai,
if it's only about closing all objects, you could create a Property, set it to close-strong and give it to H5Fopen.

Something along these lines (untested):
```csharp
var property = H5P.create(H5P.FILE_ACCESS);
H5P.set_fclose_degree(property, H5F.close_degree_t.STRONG);
var file = H5F.open("FILE_NAME", H5F.ACC_RDWR, property);
H5P.close(property);

// access file

H5F.close(file); // all objects opened are closed implicitly here
```
also have a look at the c documentation: [H5Pset_fclose_degree](https://support.hdfgroup.org/HDF5/doc/RM/RM_H5P.html#Property-SetFcloseDegree)

**Comment by LiorBanai** [comment]
Thanks @JanWosnitza ,
I'll check this out
