### ISSUE TITLE
Thread safety?

### ISSUE THREAD

**Issue by PhilPJL** [HDFGroup/HDF.PInvoke#180]
Is HDF.PInvoke.1.10.612 (.NET Standard version) thread safe?
My tests appear to say no.

**Comment by PhilPJL** [comment]
I see that calling 

```
                uint is_ts = 0;
                H5.is_library_threadsafe(ref is_ts);
```

Says it's not.  Is there a way to enable thread safety?

Shouldn't that method be an `out is_ts`?

**Comment by Apollo3zehn** [comment]
It has been built with thread-safety enabled (https://github.com/HDFGroup/HDF.PInvoke.1.10, search for `HDF5_ENABLE_THREADSAFE`).

This this thread for more information about a possible reason why your library says it is not thread-safe: https://github.com/HDFGroup/HDF.PInvoke/issues/146

**Comment by PhilPJL** [comment]
Thanks, that has sorted it.  Ran a test with multiple threads and created a 4Gb .h5 file. No issues.
