### ISSUE TITLE
Strong name validation failed

### ISSUE THREAD

**Issue by HenningOI** [HDFGroup/HDF.PInvoke#189]
On certain computers, the HDF.PInvoke dll can't be loaded:

> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'HDF.PInvoke, Version=1.10.502.0, Culture=neutral, PublicKeyToken=18793c1fcffe58a3' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)

I guess that strong name verification is somehow different on these computers due to security settings.
Can anyone help me out how I could fix it (exept compiling the dll without strong name) ?

Thanks
Lumo

**Comment by Apollo3zehn** [comment]
Do you use the [HDF.PInvoke.NETStandard](https://www.nuget.org/packages/HDF.PInvoke.NETStandard) package from surban? This is not directly related to the HDFGroup. You could try https://www.nuget.org/packages/HDF.PInvoke (.NET Framework) or https://www.nuget.org/packages/HDF.PInvoke.1.10 (.NET Core and .NET 5+) instead.

**Comment by HenningOI** [comment]
I think we are using the official nuget, version 1.10.502.0, for .net Framework.
This has a public key token:

![image](https://github.com/user-attachments/assets/67bbc40a-0a44-4fa1-9d00-9b5bb20dbbfe)

I can reproduce it by disabling the strong name bypass feature:
I added the "AllowStrongNameBypass" registry key according to 
https://learn.microsoft.com/en-us/dotnet/standard/assembly/disable-strong-name-bypass-feature#disable-the-strong-name-bypass-feature-for-all-applications

As far as I understand the exception, it happens if the public key / signature is somehow not correct.

I ran "sn -v" on the HDF.PInvoke.dll and it says "Failed to verify assembly".

**Comment by Apollo3zehn** [comment]
I was assuming you are using HDF.PInvoke.NETStandard because there is no version 1.10.502 on Nuget for HDF.PInvoke (see here: https://www.nuget.org/packages/HDF.PInvoke#versions-body-tab). But there is one for HDF.PInvoke.NETStandard (https://www.nuget.org/packages/HDF.PInvoke.NETStandard#versions-body-tab). That is why I am a bit confused :-)

**Comment by HenningOI** [comment]
I am sorry, I just got it wrong.
YES we are using the .net standard port by surban. Found the info now in the dll manifest.
We repacked this into a new nuget to make sure the c++ dlls are copied automatically, so this information was lost somehow.
