### ISSUE TITLE
What's a good framework to use for CI?

### ISSUE THREAD

**Issue by gheber** [HDFGroup/HDF.PInvoke#22]
I'm using [Travis CI](https://travis-ci.org/gheber/kenzo) for some other projects. What are people using for .NET?

**Comment by jack-pappas** [comment]
You can use Travis CI for .NET too, if you want to build and test the code using [Mono](mono/mono) (or [CoreCLR](dotnet/coreclr)) on Linux or OS X.

If you want to set up a Windows build, use [AppVeyor](http://www.appveyor.com/). It's free for open-source projects and integrates with Github like Travis CI does.

**Comment by brian-nelson** [comment]
I am using AppVeyor and have it publishing my outputs to nuget on tags/releases automatically.  I am also using CodeCov.io with the nUnit tests to calculate coverage with every build.

**Comment by hokb** [comment]
+1 for appveyor
Also heard about https://www.cloudbees.com/ but couldn't get a grasp of it yet.

**Comment by gheber** [comment]
OK, I'm just dipping my toe into the water with AppVeyor. Getting the Build configured is pretty straightforward. To run the tests, we need to bring in the native (HDF5) DLLs. What do people recommend? For starters, should I just add them to the repo and then just copy into the right place before the test run? (We'd need the 1.8.x and 1.10.x binaries in 32-bit and 64-bit.) Other suggestions?

**Comment by gheber** [comment]
Thanks for all the suggestions. Looks like we are rolling w/ AppVeyor. (@brian-nelson)
