### ISSUE TITLE
H5DO.write_chunk missing in hdf5.dll

### ISSUE THREAD

**Issue by riegaz** [HDFGroup/HDF.PInvoke#28]
I just found that you made write_chunk available and I wanted to try it but it gives me the following error:
Additional information: Unable to find an entry point named 'H5DOwrite_chunk' in DLL 'hdf5.dll'.

This function is part of the high level of HDF5.

In constants there is the dll file name defined like:

public const string DLLFileName = "hdf5.dll";

Isn't the hdf5.dll part of the high level dll? How could we fix this?

**Comment by riegaz** [comment]
I quickly tried to dllimport the hdf5_hl.dll but I get the error that the module can not be found. Why is that? Missing depencies?

**Comment by gheber** [comment]
Great catch! The symbol is in hdf5_hl.dll. Give me a minute...

**Comment by gheber** [comment]
Pull the latest version and let me know how it goes!

**Comment by riegaz** [comment]
Thanks! Works like a charm. Even though it is not part of this issue but now that there is a nuget package, where is HDF.PInvoke looking for the binaries if I do not define any path? A quick test showed me that /bin64 is not working?

**Comment by gheber** [comment]
The lookup process is described on the [front-page](../../HDF.PInvoke)  under **Dependencies**. Basically, you can set ``NativeDependenciesAbsolutePath`` in ``app.config`` or the assembly will look in ``.\bin\bin[32,64]``. Does that work for you?

**Comment by gheber** [comment]
I see what you're saying. The NuGet package has the native DLLs in ``bin[32,64]`` and not in ``lib\bin[32,64]``, where ``HDF.PInvoke`` is. Let me fix this...

**Comment by gheber** [comment]
I believe https://www.nuget.org/packages/HDF.PInvoke/1.8.16.5 has the correct paths.

**Comment by riegaz** [comment]
Installation throws errors now.

**Comment by riegaz** [comment]
MyHDF5Project (with hdf.pinvoke nuget)\
|-- bin\
|-- bin\Debug
|-- bin\bin64 <---hdf5 binaries should be in here right?

**Comment by gheber** [comment]
I see the problem: NuGet installs the package just fine, but when you build your project, ``HDF.PInvoke.dll`` gets copied to ``[Debug,Release]``, etc., but the unmanaged dependencies do not get copied. If you copy them manually into ``[Debug,Release]\[bin32,bin64]``, things work just fine. I'm out of my depth here for NuGet. What can the package do to bring the unmanaged dependencies along, when ``HDF.PInvoke.dll`` gets copied?

**Comment by riegaz** [comment]
Hm, unfortunately I can not answer this question. I just installed 1.8.16.6 and tried to copy the binaries to Debug/bin64/ manually and it does not work for me. I only installed HDF5 1.8.16 and it only finds the 1.8.12 binearies but I do not even know from where. In my environment variables there is only 1.8.16.

**Comment by gheber** [comment]
I believe NuGet package 1.8.16.8 fixes the problem. I can create a new project, install the package, and add a few HDF5 calls. As part of the build the native libraries get copied into the right places and I can run the executable. Please try!

**Comment by riegaz** [comment]
Just installed 1.8.16.8.

EntireHDF5Project (with hdf.pinvoke nuget)\
|-- HDF5Helper (nuget installed)
     |-- bin\Debug\bin[32,64] binaries are here
|-- TestApplication (HDF5Helper as Reference)
     |-- bin\Debug\bin[32,64] I copy them after build from the HDF5Helper bin/Debug/bin[32,64]

But, still HDF5 binaries from 1.8.12 are used. So environmental variables are still prefered?

**Comment by gheber** [comment]
The code to "massage" the ``PATH`` is in ``NativeDependencies.cs``. The behavior you are seeing, I believe, comes from line 84. The native directory is actually appended to the ``PATH`` rather than prepended. In your case, it picks up an "earlier" copy of ``hdf5.dll``. Maybe we should change line 84 to read
```
Environment.SetEnvironmentVariable ("PATH", string.Join(";", aPath, EnvPath));
```
?

**Comment by gheber** [comment]
@DSanchen , do you think that's a good idea?

**Comment by riegaz** [comment]
Can't we prefer the bin32/64 folders?

**Comment by DSanchen** [comment]
Hm, strange. Setting the environment variable is "only" the second try. First we try to set the DLL load directory with the SetDllDirectory() function. If that failes, the environment variable is set.
With the following code you could check, if setting the Dll Directory worked. If not, the output after DllPath should be empty... Could you try that ?
```c#
class Program
{
    static void Main(string[] args)
    {
        H5.open();
        int myFile = H5F.create("yourfilename", H5F.ACC_TRUNC);
        H5F.close(myFile);

        StringBuilder PathBld = new StringBuilder(500);
        GetDllDirectory(500, PathBld);
        Console.WriteLine("DllPath: {0}", PathBld.ToString());
        Console.ReadKey(true);

        H5.close();
    }

    [DllImport("kernel32.dll",CallingConvention =CallingConvention.Winapi,SetLastError = true)]
    public static extern int GetDllDirectory(int nBufferLength, StringBuilder lpBuffer);
}
```

Apart from that, I see no real problem in prepending the PATH variable, as gheber suggested...

**Comment by gheber** [comment]
With the current NuGet (1.8.16.8) I'm getting
``DllPath: c:\users\gerd\documents\visual studio 2013\Projects\ConsoleApplication1\ConsoleApplication1\bin\Debug\bin32``
which is the right thing.

**Comment by riegaz** [comment]
For me it gives: {C:\Program Files (x86)\Intel\OpenCL SDK\5.3\bin\x86}, which is one of the Directories within my PATH variable.

**Comment by gheber** [comment]
Have you tried setting ``NativeDependenciesAbsolutePath`` in ``app.config``?

**Comment by riegaz** [comment]
Not yet, I will do that now. However, I do not see how a absolute path will help me to provide an application that has to run on several devices later on? For development I can absolutely see your point. Do I then have to relay on the PATH variables? The relative folders bin32/bin64 would do the job more efficiently.

**Comment by DSanchen** [comment]
@riegaz could be that OpenCL also uses the SetDllDirectory function *after* the HDF.Pinvoke-call. In this case we would *need* to use the PATH variable, as we can there have many locations... 
If this is the issue, it would mean that your PATH variable does not contain the folders we are expecting. Could you verify that by adding this output to the above console app (before console.ReadKey):
```c#
console.WriteLine("Assembly's PATH: {0}", Environment.GetEnvironmentVariable("PATH"));
```

**Comment by DSanchen** [comment]
Now you should be able to either use the relative bin32/64 folders or the app.config approach. The latter makes sense if you install your application + your dependencies into a known path and want to make sure that exacly that installed path is used...

**Comment by riegaz** [comment]
@DSanchen I just used your command and it gives me all the variables from my PATH except the one for the hdf5.

> DllPath: C:\Program Files (x86)\Intel\OpenCL SDK\5.3\bin\x86
Assembly's PATH: D:\cygwin\bin;D:\cygwin\usr\local\IMOD\bin;C:\Program Files (x86)\Intel\OpenCL SDK\5.3\bin\x64;C:\Program Files (x86)\Intel\OpenCL SDK\5.3\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\5.3\bin\Pin;C:\Program Files (x86)\Intel\OpenCL SDK\5.3\bin\GTPin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;

But the hdf5 is listed when I check the variables from Windows system view.

**Comment by riegaz** [comment]
@DSanchen I just made the changes to the NativeDependencies.cs but nothing changed. Same DLL Paths.

**Comment by hokb** [comment]
Not directly related, but I am not sure if SettDllDir brings more advantages than potential pitfalls. It replaces the current search path, hence may misconfigure other libraries, no?

From [msdn](https://msdn.microsoft.com/de-de/library/windows/desktop/ms686203%28v=vs.85%29.aspx):
"Each time the SetDllDirectory function is called, it replaces the directory specified in the previous SetDllDirectory call. To specify more than one directory, use the AddDllDirectory function and call LoadLibraryEx with LOAD_LIBRARY_SEARCH_USER_DIRS."

Besides that, the PATH configuration stuff seems reasonable now. It might be useful to have a `Trace.WriteLine(newPath)` in `AddPathStringToEnvironment` to be able to check, whether the folders have been set up correctly.

**Comment by DSanchen** [comment]
With the latest commit, neither the DllPath nor the Assembly's path contain "your" folder ? :confused:

**Comment by riegaz** [comment]
No, unfortunately not. The assembly path printed out is first the PATH from the system variables (without my HDF5 1.8.16 path, which is there when I check in Windows) and then appended there is the PATH from the user variables.

**Comment by DSanchen** [comment]
@riegaz could you add this line to the console app (just before H5.open)
```c#
System.Diagnostics.Trace.Listeners.Add(new System.Diagnostics.ConsoleTraceListener());
```
and this to the NativeDependencies.cs, right after SetEnvironmentVariable()
```c#
System.Diagnostics.Trace.WriteLine(string.Format("{0} added to Path.", aPath));
```
?

**Comment by DSanchen** [comment]
@hokb I also saw that msdn article and did't want to rely on any patches for AddDllDirectory... Maybe you're right and we should only rely on the PATH...

**Comment by riegaz** [comment]
@DSanchen I added both lines but I do not get any output. I can set a debug point within the NativeDependencies.cs but it never got hit.

**Comment by DSanchen** [comment]
?? Stepping through NativeDependencies.cs, can you tell me what is returned by GetAssemblyName() ?

**Comment by riegaz** [comment]
It seems the entire class never gets called. I copied the content of the GetAssemblyName() now into my consoleapplication and it gives me back the right thing.

> ConsoleApplication1/bin/Debug/ConsoleApplication1.EXE

Could it be that the H5public constructor is never called?

**Comment by DSanchen** [comment]
It's the H5 static constructor. One of the H5 fuctions (e.g. H5.open()) need to be called in order to have set up things right.

**Comment by riegaz** [comment]
Ok, for my example program I do only create a hdf5 file and write stuff into it. I do not open it. Could that be a problem? I can not find the h5.create within the h5 static constructor?!

**Comment by DSanchen** [comment]
H5.open() initializes the HDF library. It has nothing to do with opening a file. Just **DO** call H5.open().

**Comment by riegaz** [comment]
Now everything works. My fault, I'm feeling sorry now.

**Comment by DSanchen** [comment]
Glad that it's working now.
0b2daccd57c45d0449e6b99dbf01b10765ac020f addresses hokb's suggestion.
Modified the Readme to include H5.open()...

**Comment by gheber** [comment]
I love to come to the office in the morning only to find that you've solved all problems. Thanks all for chiming in. Practically every day I do learn something from these exchanges. GitHub is a wonderful tool, but it takes the right people to make it work.
