### ISSUE TITLE
How to deal with / mark thread safety 

### ISSUE THREAD

**Issue by hokb** [HDFGroup/HDF.PInvoke#31]
=== This is NOT related to SWMR in 1.10. === 

Is HDF.PInvoke thread safe? Means, can I call the same function from multiple threads / AppDomains concurrently as long as I am working in individual files? 

@gheber  Maybe we could have another wiki page (hope, I haven't missed it somewhere?) and put some related content / links to such content from/ to the official docs?

**Comment by gheber** [comment]
Yes, HDF.Pinvoke is thread safe IF you are using an HDF5 DLL that was built with thread-safety enabled. It's thread safe for threads in the same OS process. There are a few examples in ``H5TSTest``.  Starting with HDF5 1.8.16 there is an API call, ``H5.is_library_threadsafe``, to find out if the currently loaded library is thread safe. That might be another thing to add to OUR configuration. A developer might declare in ``app.config`` that thread-safety is a requirement, and the application should abort in case it finds only a non-threadsafe build. Wiki page is a good idea.

**Comment by hokb** [comment]
I see. I think we (ILNumerics) possibly stumbled upon this already. Which drawbacks would be introduced when always using the threadsafe build only? Or putting it in another way: what **advantage **one gets by using a non-threadsafe build?

**Comment by gheber** [comment]
On Windows, I use thread-safe builds only. I have not done a performance comparison between the two versions. There's some overhead to be expected from the additional protection (mutex) in a thread-safe build, but my guess is that it's insignificant for a single-threaded application, because lock acquisition always succeeds on the first attempt. I'm not aware of any downsides.

**Comment by gheber** [comment]
The binaries included in the NuGet package are thread-safe.

**Comment by hokb** [comment]
great. Thanks! I guess we should simply go the threadsafe way. Potentially, we might give the option to check which version is being used, as you mentioned above. But according to the no-code rule this would go into a higher level layer.
