### ISSUE TITLE
H5Aiterate_by_nameTest1 fails occasionally.

### ISSUE THREAD

**Issue by gheber** [HDFGroup/HDF.PInvoke#35]
I believe we are too sloppy with the `op_data`. We can't pin the `ArrayList` properly, and should switch to something which can be pinned.

**Comment by hokb** [comment]
I've tried to implement something here. Please [review](https://github.com/HDFGroup/HDF.PInvoke/compare/master@%7B1467926549%7D...master)! (I realized too late that I seem to have commit perm on master. I guess I should use branches and pull requests for future changes...)

**Comment by DSanchen** [comment]
Looks good... Anything that cannot be moved by the .NET runtime during the iteration-process should work... Address -99 should be fixed (wherever that "Address" lies :smile:)

**Comment by hokb** [comment]
I dunno where it points to. The purpose of the test it to check the API of the method and to see if the same 'address' ends up in the callback function. AFAIU the callback function is the only place where the pointer is referenced. So for this test we should be fine, no?
