### ISSUE TITLE
How to handle the 1.8 and 1.10 configurations in the same solution?

### ISSUE THREAD

**Issue by gheber** [HDFGroup/HDF.PInvoke#36]
At the moment the process is manual and error prone. One has to define HDF5_VER1_10 (and make sure that the unit tests pick up the right DLLs). What does the *sophisticated* configuration manager do in a situation like that?

**Comment by hokb** [comment]
I don't know. Will it be likely for someone to frequently switch target versions? If not, the effort of having to define a single compilation symbol sounds not too demanding?

**Comment by gheber** [comment]
That sounds reasonable. I'd say people will switch infrequently, if at all. They can always use the NuGet package kick the (new) tires.
