### ISSUE TITLE
Using your latest 1.10.0-pre2 nuget package, H5D.open returns 4294967295 instead of -1 

### ISSUE THREAD

**Issue by riegaz** [HDFGroup/HDF.PInvoke#38]
I just updated to your latest release.

Now H5D.open(id, name) returns 4294967295 instead of -1 if the dataset is not found. Is this is a new convention?

**Comment by gheber** [comment]
Thanks for trying! One of the main differences between the 1.8 and 1.10 families of HDF5 is that the `hid_t` handle type changed from `System.Int32` to `System.Int64`. You should see a return type of `long` instead of `int` in the documentation and in IntelliSense. Do you have an example?

**Comment by riegaz** [comment]
@gheber I quickly tried to just create a file and open a dataset that not exists and the return value is -1. For some reason, for the same hdf5 file I get the 4294967295 within my project. I will investigate a little and come back once I figured it out. So far I do not see any difference because I only open the file and try to open several datasets.

**Comment by gheber** [comment]
4294967295 = 2^32 − 1. You're seeing an over/underflow. The return value of H5D.open is `System.Int32` in HDF5 1.8.x, but it is `System.Int64` in HDF5 1,10.x. Yes, -1 = -1, but `((System.Int32) -1) <> ((System.Int64) -1)`.

**Comment by riegaz** [comment]
I also expected that to be an overflow problem, but how comes. I mean all I do is
long dataSet = H5D.open(id, name);
and it returns 4294967295 instead of -1.

Does your nuget package install the required HDF5 1.10 DLLs and does it use them correctly?

**Comment by gheber** [comment]
When I build and run the attached project, I see this output:
```
HDF5-DIAG: Error detected in HDF5 (1.10.0-pre2) thread 4896:
  #000: C:\build\HDF5\1.10.0\CMake-hdf5-1.10.0-pre2\hdf5-1.10.0-pre2\src\H5D.c line 296 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: C:\build\HDF5\1.10.0\CMake-hdf5-1.10.0-pre2\hdf5-1.10.0-pre2\src\H5Dint.c line 1455 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #002: C:\build\HDF5\1.10.0\CMake-hdf5-1.10.0-pre2\hdf5-1.10.0-pre2\src\H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: C:\build\HDF5\1.10.0\CMake-hdf5-1.10.0-pre2\hdf5-1.10.0-pre2\src\H5Gtraverse.c line 869 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: C:\build\HDF5\1.10.0\CMake-hdf5-1.10.0-pre2\hdf5-1.10.0-pre2\src\H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: C:\build\HDF5\1.10.0\CMake-hdf5-1.10.0-pre2\hdf5-1.10.0-pre2\src\H5Gloc.c line 385 in H5G_loc_find_cb(): object 'non-such' doesn't exist
    major: Symbol table
    minor: Object not found
-1

Press any key to continue...
```

What do you see?

[ConsoleApplication1.zip](https://github.com/HDFGroup/HDF.PInvoke/files/188877/ConsoleApplication1.zip)

**Comment by gheber** [comment]
(The error stack from HDF5 is just a verbose way of saying that there is no such dataset.)

**Comment by riegaz** [comment]
@gheber I found the problem. Somehow the post build event commands got lost. Therefore, I guess, it used the old HDF5 1.8.xx version. I added the post build event commands now and it works. I was not able to see the error stack because I'm working on a WPF C # project.

**Comment by gheber** [comment]
Glad to hear you got that sorted.
