### ISSUE TITLE
NuGet updates do not remove event commands

### ISSUE THREAD

**Issue by riegaz** [HDFGroup/HDF.PInvoke#49]
The update from HDF.PInvoke.1.10.0-pre2 to HDF.PInvoke.1.10.0-pre3 did not remove the event commands. This is also why [this ](https://github.com/HDFGroup/HDF.PInvoke/issues/38)problem arised. Is there a possibility to remove the old ones when updating?

**Comment by gheber** [comment]
When you say 'event commands', do you mean the PowerShell scripts?

**Comment by riegaz** [comment]
I mean the post build commands.

if not exist "$(TargetDir)bin32" md "$(TargetDir)bin32"
xcopy /s /y "$(SolutionDir)packages\HDF.PInvoke.1.10.0-pre3\lib\native\bin32\*.*" "$(TargetDir)bin32"
if not exist "$(TargetDir)bin64" md "$(TargetDir)bin64"
xcopy /s /y "$(SolutionDir)packages\HDF.PInvoke.1.10.0-pre3\lib\native\bin64\*.*" "$(TargetDir)bin64"

**Comment by gheber** [comment]
The combination of `Install.ps1` and `GetHDFPostBuildCmd.ps1` copies the unmanaged HDF5 DLLs to the `bin32` and `bin64` sub-directories of a solution's target directory. I could try to first remove existing DLLs explicitly, but the `xcopy` command already uses the `/y` option to suppress prompting to overwrite existing files. Of course, if a DLL is currently loaded, it can't be overwritten, but it can't be removed either. What am I missing?
