### ISSUE TITLE
Please include a copy of the license in the repository, for easy reference and clarity

### ISSUE THREAD

**Issue by basbossink** [HDFGroup/HDF.PInvoke#50]
When opening/viewing the HDF.PInvoke  repository it is not clear under what license the software is made available. I know it is available from http://www.hdfgroup.org/HDF5/doc/Copyright.html since this reference is given in the source code and the nuspec files. However it would be much nicer if a LICENSE file would be present in the root of the repository. 

Furthermore I think the Readme.md should also have paragraph that discusses the licensing terms and a reference to the actual license.

**Comment by gheber** [comment]
Thank you for the suggestion. Do 390f272 and c456899 cover your concerns?

**Comment by basbossink** [comment]
Thank you for picking this up so quickly. Yes this covers my concerns, thank you very much.
