### ISSUE TITLE
H5A.read NATIVE_INT appears to treat the attribute as an unsigned integer

### ISSUE THREAD

**Issue by obergshavefun** [HDFGroup/HDF.PInvoke#53]
The following code stores -1 into the HDF5 file as an 8-bit integer:

      int value = -1;
      hid_t attributeSpace = -1;
      hid_t typeId = -1;
      hid_t attributeId = -1;

      try
      {
        attributeSpace = H5S.create(H5S.class_t.SCALAR);
        typeId = H5T.copy(H5T.NATIVE_INT);
        H5T.set_size(typeId, new IntPtr(1));
        attributeId = H5A.create(objectId, title, typeId, attributeSpace);

        var array = new int[] { value };
        GCHandle pinnedArray = GCHandle.Alloc(array, GCHandleType.Pinned);
        H5A.write(attributeId, typeId, pinnedArray.AddrOfPinnedObject());
        pinnedArray.Free();

        return true;
      }
      catch (Exception ex)
      {
        return false;
      }
      finally
      {
        if (attributeId != -1) H5A.close(attributeId);
        if (typeId != -1) H5T.close(typeId);
        if (attributeSpace != -1) H5S.close(attributeSpace);
      }

When reading the same value back in, it returns 255, appearing to treat the NATIVE_INT as an unsigned 8-bit integer.  Based on the documentation, I do not expect this to occur.

      int value = -9999999;

      if (H5A.exists(objectId, title) == 0)
      {
        return false;
      }

      hid_t typeId = -1;
      hid_t attributeId = -1;

      try
      {
        typeId = H5T.copy(H5T.NATIVE_INT);
        H5T.set_size(typeId, new IntPtr(1));
        attributeId = H5A.open(objectId, title);
        if (attributeId == -1)
          return false;

        int[] array = new int[1];
        GCHandle pinnedArray = GCHandle.Alloc(array, GCHandleType.Pinned);
        H5A.read(attributeId, typeId, pinnedArray.AddrOfPinnedObject());
        pinnedArray.Free();

        value = array[0];

        return true;
      }
      catch (Exception ex)
      {
        if (logError)
        {
          log.Error("Exception in reading attribute: {0}", ex.Message);
        }
        return false;
      }
      finally
      {
        if (typeId != -1) H5T.close(typeId);
        if (attributeId != -1) H5A.close(attributeId);
      }

**Comment by brian-nelson** [comment]
I am reading attributes similar to what you are doing in my own project but I do not call

    H5T.set_size(typeId, new IntPtr(1));

I rely on the size from the H5T.copy(H5T.NATIVE_INT)

Not sure if that helps.

**Comment by obergshavefun** [comment]
That solves the problem.  Thank you.
