### ISSUE TITLE
2D jagged variable string array write, read, extend

### ISSUE THREAD

**Issue by riegaz** [HDFGroup/HDF.PInvoke#58]
I found [this example](https://github.com/HDFGroup/HDF.PInvoke/blob/4e4620b9ccfe01cdff419585d240ed7fe552ffe9/UnitTests/H5DTest/H5Dvlen_reclaim.cs) to create a 1D array with variable length writing and reading.

I was wondering how to modify to allow the same for 2D? Also extending this 2D array would be interesting.

Let's say I know from the beginning the number of columns but I then want to add a variable number of rows to each column. This should be possible at any time (extend).

```
-------a------------b-----------c------------d-----------e-----------f------
|           ||           ||           ||           ||           ||           |
      a1          b1           c1           d1           e1           f1
      a2          b2           c2           d2           e2           f2
      a3                       c3           d3           e3           f3
      a4                                    d4           e4           f4
      a5                                    d5           e5              
      a6                                    d6           e7              
                                                         e8              
```

I think in general this is possible right? How would I do with this library?

**Comment by gheber** [comment]
HDF5 datasets are (logically) dense arrays. Depending on element type,
sparsity, access, and dynamics, you can come up with different strategies
to mimic a jagged array. A few examples:

1. Assuming your element type is just a scalar type such as integers,
   floats, or strings, you could just use a chunked 2D dataset
   with one or two infinite dimensions. The library will allocate only chunks
   where you put values, and compression will take care of fill values (0) on
   a chunk.
   
2. You could have a one-dimensional dataset, representing the columns, where
   the dataset element type is a variable-length sequence, representing the rows
   in a given column, of the "cell" type (int, float, etc.)
   In that case, you would need an additional dataset of the same structure
   to store the row IDs of cells. Depending on how frequently entries are
   added/remove, you'd have to update/sort that "descriptor" dataset.
   
There are many other variants, but the fact remains that 1) there is no
"native" HDF5 primitive for representing jagged arrays, and 2) the cocktail
of primitives that might achieve your goal(s) depends on several factors
(element type, sparsity, access, and dynamics).

**Comment by riegaz** [comment]
@gheber thanks for your answer, with your two examples I found a fitting solution for me.
