### ISSUE TITLE
Compound datatype example

### ISSUE THREAD

**Issue by riegaz** [HDFGroup/HDF.PInvoke#59]
Could you provide an example or unittest for how to use this library with compound datasets? Similar to [here](https://www.hdfgroup.org/HDF5/doc/cpplus_RM/compound_8cpp-example.html)?

**Comment by DSanchen** [comment]
Right now there is no support for High-Level APIs like CompType or other types from the C++ Library. If you need them, you can P/Invoke them as needed. 
Currently HDF.PInvoke supports the basic HDF5-functions without any added value or higher abstraction...

**Comment by riegaz** [comment]
Thanks a lot.
