### ISSUE TITLE
strong naming

### ISSUE THREAD

**Issue by reyntjesr** [HDFGroup/HDF.PInvoke#60]
Could you please strong name sign your library? When I add it to a project via nuget I get an error message that your dll doesn't have a strong name. There are workarounds for this problem but it would be much easier if you give HDF.Pinvoke a strong name.
By the way I created a [project on github](https://github.com/reyntjesr/Hdf5DotnetTools) that uses your library. It's still in its early stages and there are still some [issues](https://github.com/reyntjesr/Hdf5DotnetTools/issues) I need help with. Any other suggestions are also welcome.

Thanks by the way for this project. Your unit tests were a lot of help to me in understanding how to read and write hdf-5 files.

**Comment by gheber** [comment]
I'll try to get this done for the NuGet package release at the end of the month.

**Comment by hokb** [comment]
+1 - stumbled upon it today. Btw, we will replace our internal PINVOKE defs with HDF.PInvoke with the next release of ILNumerics. Would be great to be able to use the nuget packages instead of the projects code.

**Comment by gheber** [comment]
It's on the radar and I'm trying to roll this in after I'm done w/ the SWMR tests.

**Comment by hokb** [comment]
Sounds awesome. Thanks

**Comment by gheber** [comment]
52ea197

**Comment by gheber** [comment]
I've pushed two new NuGet packages 1.8.17.2 and 1.10.0-pre4. Both should have strong names. @reyntjesr would you mind checking them out?

**Comment by reyntjesr** [comment]
I tested the nuget package 1.8.17.2 and it works now. 

I also tried the 1.10 version and I don't get a strong name error either. My library however doesn't work with this new version but that is another problem I think and I will have to look into that later when I have more time.

**Comment by gheber** [comment]
Great. Thanks for testing.
