### ISSUE TITLE
H5L.iterate can not handle any other index value than H5.index_t.NAME

### ISSUE THREAD

**Issue by basbossink** [HDFGroup/HDF.PInvoke#61]
While using the H5L.iterate method I found it fails when any other value than H5.index_t.NAME is used for the index parameter. I've adapted the H5LIterate test to be a reproduction scenario for this issue, in [this commit](https://github.com/basbossink/HDF.PInvoke/commit/beb919c41eedb513ed27a2d2b50b1e4b9dc25448).

**Comment by gheber** [comment]
Have you enabled link creation order tracking and indexing on the group (via `H5Pset_link_creation_order`)? Unless a group is created with this property set, the index is not created/maintained, and `H5L.iterate` will fail. (Link names are always indexed and tracked.)

**Comment by basbossink** [comment]
Sorry for the late response. To answer you're question, no I have not used that call. I'll give it a try and get back to you.

**Comment by basbossink** [comment]
I tried to use the method in the following way:

            var groupId = H5G.create(locationId.RawHandle, groupName);
            var propertyGroupCreationList = H5G.get_create_plist(groupId);
            var propertyResult = H5P.set_link_creation_order(propertyGroupCreationList, H5P.CRT_ORDER_INDEXED);
            

But that does not seem to work. Actually the ordering in my case was not important. So I'll stick with the H5.index_t.NAME for know.

**Comment by gheber** [comment]
Almost there. The creation properties must be set on group creation, not afterwards. Try this:
```
var gcpl = H5P.create(H5P.GROUP_CREATE);
var propertyResult = H5P.set_link_creation_order(propertyGroupCreationList, H5P.CRT_ORDER_INDEXED);
var groupId = H5G.create(locationId.RawHandle, groupName, gcpl);
...
```
Does that work for you?

**Comment by gheber** [comment]
Any luck?

**Comment by basbossink** [comment]
Sorry for responding so late. Thanks for your help as I mentioned earlier the actual ordering was not important. So I haven't gotten around to trying your suggestion. I've used the property list to set the chunking properties of a data set and I'm beginning to understand how it works. I hope I have some time to try out your suggestion in the near future.
