### ISSUE TITLE
IntPtr overloads for System.Array arguments

### ISSUE THREAD

**Issue by hokb** [HDFGroup/HDF.PInvoke#63]
Considering functions which receive or give back data in terms of arrays, as in H5Apublic.cs: 
`public extern static ssize_t get_name_by_idx
            (hid_t loc_id, byte[] obj_name,
            H5.index_t idx_type, H5.iter_order_t order, hsize_t n,
            [Out] byte[] name, size_t size, hid_t lapl_id = H5P.DEFAULT);`

It is often useful to have the chance to access the function and provide a pointer intsted of a `byte[]`. Reason: latter needs to live on the heap. `IntPtr` can live on the [stack](https://msdn.microsoft.com/en-us/library/cx9s2sy4(v=vs.100).aspx). Often the data can be considered temporary anyway and need to be reworked in the calling function. Hence, this is a perfect place for stackalloc. 

We should consider adding corresponding overloads on all places where IntPtr would be feasible? 
`public extern static ssize_t get_name_by_idx
            (hid_t loc_id, byte[] obj_name,
            H5.index_t idx_type, H5.iter_order_t order, hsize_t n,
            IntPtr name, size_t size, hid_t lapl_id = H5P.DEFAULT);`

**Comment by DSanchen** [comment]
Like this: ?
```c# 
public extern static ssize_t get_name(hid_t attr_id, size_t size, IntPtr name);
```
---
```c#
   [TestMethod]
   public unsafe void H5Aget_nameTest5()
   {
       size_t buf_size = IntPtr.Zero;
       ssize_t size = IntPtr.Zero;
       hid_t att = H5A.create(m_v2_test_file, "H5Aget_name", H5T.IEEE_F64LE, m_space_scalar);
       Assert.IsTrue(att >= 0);

       // pretend we don't know the size
       size = H5A.get_name(att, buf_size, IntPtr.Zero);
       Assert.IsTrue(size.ToInt32() == 11);
       buf_size = new IntPtr(size.ToInt32() + 1);

       char* namePtr = stackalloc char[(int)buf_size];
       size = H5A.get_name(att, buf_size, (IntPtr)namePtr);
       Assert.IsTrue(size.ToInt32() == 11);
       string name = Marshal.PtrToStringAnsi((IntPtr)namePtr);
       // names should match
       Assert.AreEqual("H5Aget_name", name);
   }
```
I'm not working with unsafe code so I never came around stackalloc until now. Do you use it for performance reasons ?

**Comment by hokb** [comment]
Exactly. In this particular example we probably could get away with StringBuilder or [MarshalAs] on a plain string (have not tried though). stackallow becomes even more useful if you just need a temporary int[] array for defining dimension lengths or hyperslab parameters a.t.l. 
stackalloc also often allows to write code which is free of `new` statements, which can be of advantage in multithreaded setups to prevent from contention by global locks.

We are currently integrating HDF.PInvoke into ILNumerics.IO.HDF and will add pointer overloads at all places we find useful. However, we do not cover all features of HDF5 yet.

**Comment by hokb** [comment]
Basically, those pointer overloads must simply reflect the HDF5 C API in a 1:1 manner.

**Comment by gheber** [comment]
I'd be fine with that. Let's discuss this at the next pow wow!

**Comment by gheber** [comment]
See issue #72 as a first step. More to come as needed/requested.

**Comment by hokb** [comment]
tested and working fine. (nuget 1.8.17.2, 1.10)
