### ISSUE TITLE
Versioning scheme

### ISSUE THREAD

**Issue by hokb** [HDFGroup/HDF.PInvoke#66]
Currently, AssemblyInfo.cs defines the versions as: 

````
#if HDF5_VER1_10
[assembly: AssemblyVersion("1.10.0.*")]
[assembly: AssemblyFileVersion("1.10.0.*")] 
#else
[assembly: AssemblyVersion("1.8.17.*")]
[assembly: AssemblyFileVersion("1.8.17.*")]
#endif
````

This gives a warning during build since Assembly***File***Version does not support the asterisk (while AssemblyVersion does).
Versioning is really important in .NET so it is rather important to make a conscious decision about which versionin scheme we want to follow for HDF.PInvoke. 
`AssemblyVersion` is used in order to identify a strongly named assembly in DLL probing. Using the '*' here can lead to surprises on the user side. Commonly, updates of the same major, minor version should be distributed as drop-in replacements for the older, buggy version. (At least this is how Microsoft does it). So the build and revision numbers would not change for patches and bugfixing updates on the same major, minor version. Replacing them is easy for the user: she does not need to change any project references etc. The new DLL simply replaces the old one. 
In order to distinguish actual builds the `AssemblyFileVersion` is of more use. This is the one displayed in the properties window when right-clicking on a dll file and selecting "Properties", among other places.

My recommendation would be to keep AssemblyVersion the same except for minor and major updates. And to use an auto-incrementing scheme for AssemblyFileVersion. Now it is too bad that there is no real easy way of auto-incrementing the AssemblyFileVersion. Commonly, people use msbuild or VisualStudio trickery to achieve this.

**Comment by gheber** [comment]
I agree & vaguely remember doing some weird VS stuff to automate that. Let's talk about how to implement this at our next pow wow.

**Comment by gheber** [comment]
For the time being, we'll update `AssemblyFileVersion` for each release.
