### ISSUE TITLE
Warn the user that the Visual C++ 2013 Runtime is needed.

### ISSUE THREAD

**Issue by gheber** [HDFGroup/HDF.PInvoke#79]
I can see that the solution proposed in [this discussion](http://stackoverflow.com/questions/33779063/nuget-package-with-a-dependency-on-visual-c-2013-runtime) might be useful. What are others thinking?

**Comment by DSanchen** [comment]
Looks reasonable. The static NativeDependencies class would obviously be a nice place for that "Assert" function....

**Comment by hokb** [comment]
Sorry for the late comment [here](https://github.com/HDFGroup/HDF.PInvoke/pull/80#issuecomment-238289219).
