### ISSUE TITLE
FORTRAN - C API type mappings

### ISSUE THREAD

**Issue by hokb** [HDFGroup/HDF.PInvoke#88]
Since HDF.PInvoke uses the C API of HDF5 (correct me if am wrong) there should be some mapping table which helps to translate individual types from one API to the other. 

Example: 
A user stores a string using the FORTRAN API. The string ends up in the HDF5 file with the base datatype H5T_NATIVE_CHARACTER. Which datatype this translates to when reading the string using the C API, HDF.PInvoke respectively? 

It seems that not all predefined datatypes listed [here](https://www.hdfgroup.org/HDF5/doc/RM/PredefDTypes.html) are provided in[ H5T](https://github.com/HDFGroup/HDF.PInvoke/blob/master/HDF5/H5Tglobals.cs) (or in the [CSV definition fil](https://github.com/HDFGroup/HDF.PInvoke/blob/master/HDF5/H5Tglobals.csv)e). I wonder if this is intended and what is the background on it?

**Comment by hokb** [comment]
Or to put it into other words: currently it is not possible to create ALL predefined data types in HDF5 utilizing HDF.PInvoke / the C API. 

H5T_NATIVE_CHAR and H5T_NATIVE_CHARACTER are two examples. For me it seems like the result would be a limited compatibility between the APIs - which sounds strange to me (HDF was made for compatibility?). So there must be some way to create the very same HDF5 file, regardless which API was used to create it, right? Any pointers ?

**Comment by gheber** [comment]
> A user stores a string using the FORTRAN API. The string ends up in the HDF5 file with the base datatype H5T_NATIVE_CHARACTER. Which datatype this translates to when reading the string using the C API, HDF.PInvoke respectively?

The in-memory type specified in the operation, e.g., H5Dread, determines how the library converts the in-file type. It doesn't really matter how it's stored in the file. The application tells the library what it wants (in-memory), and that's what it gets. At the lowest level, HDF.PInvoke always want's C-strings, ASCII or UTF-8 encoded, null-terminated byte strings.

**Comment by gheber** [comment]
The same goes for writing. The in-file type determines how it gets written to the file. C-applications can write strings as FORTRAN strings, or little-endian floating-point numbers in-memory as big-endian in the file.

**Comment by gheber** [comment]
I will add the missing built-in types. No particular reason to omit or include them.

**Comment by hokb** [comment]
Sounds great. Thanks!
