### ISSUE TITLE
UTF8 fixed length string dataset / attribute

### ISSUE THREAD

**Issue by hokb** [HDFGroup/HDF.PInvoke#91]
HDF5 allows to create variable length _and_ fixed length string arrays as datasets and/or attributes. At the same time it allows to store encoded characters in those elements. Now, the _length_ of such elements corresponds to the number of _encoded bytes_ - not the number of _characters_ ([ref](https://www.hdfgroup.org/HDF5/doc/RM/RM_H5T.html#Datatype-SetSize))

IMO this does not play so well with fixed length strings? UTF8 encodes characters to either 1....4 bytes, depending on the unicode code point. Introducing a fixed number of bytes for the final encoded number of bytes leads to either corrupted characters if not all bytes of an encoded byte sequence fit into the remaining bytes of a cell. Or a more sophisticated client could cut off the last character and replace the remaining bytes with the pad bytes. But this is equally wrong since it leads one to believe that the original string was shorter than expected. 

Is there any official way out? A handling guideline on fixed length UTF8 strings? Or is this combination discouraged?

**Comment by gheber** [comment]
Correct. The definition of fixed-length string datatype is *misleading* for UTF-8 encoded strings. It should be called *fixed byte capacity string*. There is no "official way out". Applications must check if the byte capacity of the string datatype is sufficient for the UTF-8 encoded byte sequence to be written, and take action if it is insufficient. If an application wants to store up to `N` Unicode code points, then it would be prudent to create a fixed-length string type with a capacity of `4*N` bytes.
