### ISSUE TITLE
Check multithreaded access

### ISSUE THREAD

**Issue by hokb** [HDFGroup/HDF.PInvoke#96]
Using the wrapper from multiple threads causes sproadic AccessViolationExceptions.

**Comment by hokb** [comment]
One potential candidate: H5Public.

**Comment by hokb** [comment]
Initialization from multiple threads: does one need to initialize the library with H5.open() *from each thread*? Currently we initialize it automatically *from the main thread* only (in each static H5??? constructor).

**Comment by gheber** [comment]
`H5.open()` must be called once by a thread in a process *before* any other HDF5 functions are invoked. Calling it more than once (per process) is unnecessary, and has no side effects.

**Comment by gheber** [comment]
The values for library globals, such as `FILE_CREATE`, are (once initialized) the same for the library instance and all threads in the hosting process.

**Comment by gheber** [comment]
The code inside the getter should be a critical section. (?)

**Comment by hokb** [comment]
Looks like this snippet is able to reproduce the issue: 

    class Program
    {
        static void Main(string[] args)
        {
            Thread t1 = new Thread(new ParameterizedThreadStart(DoWork));
            Thread t2 = new Thread(new ParameterizedThreadStart(DoWork));

            // start two threads
            t1.Start(Guid.NewGuid().ToString() + ".hdf5");
            t2.Start(Guid.NewGuid().ToString() + ".hdf5");

            // ... from the main thread
            DoWork("main.hdf5");

            t1.Join();
            t2.Join();

            Console.ReadLine();
        }

        public static void DoWork(object filename)
        {
            Console.WriteLine("starting " + filename);

            HDF.PInvoke.H5.open();

            StringBuilder sb = new StringBuilder();

            for (int i = 0; i < 10000; i++)
            {
                //short[] buffer = new short[9800];
                HDF.PInvoke.H5E.walk_t cb = (uint n, ref HDF.PInvoke.H5E.error_t err_d, IntPtr client_data) => {
                    sb.Append(err_d.desc);
                    return 1;
                };
                int err = HDF.PInvoke.H5E.walk(HDF.PInvoke.H5E.get_current_stack(), HDF.PInvoke.H5E.direction_t.H5E_WALK_DOWNWARD, cb, IntPtr.Zero);
            }

            Console.WriteLine("finished " + filename);
        }
    }

Interestingly enough AccessViolationException appears to happen on the 32bit platform only. On 64bit I ran it for like 10 times and all of them succeeded without any exception. Maybe we should check if we have the right binaries? Any chance a non-threaded version slipped into the package somehow?

**Comment by hokb** [comment]
@gheber  thanks for this important confirmation (call `open()` once is sufficient and all globals are the same for all threads).

> The code inside the getter should be a critical section. (?)
Hm. Scratching my head... I don't see any reason for it? All WINAPI functions we are calling inside the getters are threadsafe with the exception of GetModuleHandle. But latter should not conflict since we are not calling FreeLibrary anywhere. At worst LoadLibrary is called multiple times on the same module which should not do any harm? Also aside from `m_importer.GetValue<hid_t>()` we might assign the cach multiple times, again without harm ... (actually ;)).

**Comment by gheber** [comment]
I can't make it fail here (either 32-bit or 63-bit). I'll rebuild the DLLs and send you a new version. Is it possible that it picks up something else in your path?

**Comment by gheber** [comment]
Are the writes, such as `H5P_CLS_FILE_CREATE_g = val;` atomic?

**Comment by hokb** [comment]
On 32bit they should. 32bit assignments are atomic. For 64 bit we should use `System.Threading.Interlocked` though.

**Comment by hokb** [comment]
Oh and for 1.10, where we have 64 bit hid_t `System.Threading.Interlock` will be useful in general.

**Comment by hokb** [comment]
> Is it possible that it picks up something else in your path?
Sure it is! :) I had to recall the [dll probing order](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx#search_order_for_desktop_applications) and realized that the System folder is searched *before* the PATH folders. Now I have an installation from the official HDF Group installer (32bit) on my system. Hence this was picked up first. Apparently this is not thread safe. Anyway, thanks for helping tracking this down!
